FROM rockylinux:8

RUN dnf update -y && dnf install -y sudo dnf 'dnf-command(download)' git && dnf clean all

RUN mkdir /tmp/scripts && mkdir /tmp/target-scripts
COPY ./*.sh /tmp/
COPY scripts/*.sh /tmp/scripts/
COPY target-scripts/*.sh /tmp/target-scripts/
RUN cd /tmp && ./precheck.sh && ./prepare-pkgs.sh && dnf clean all
