FROM rockylinux/rockylinux:10

RUN dnf update -y && dnf install -y sudo dnf 'dnf-command(download)' && dnf clean all

RUN mkdir /root/scripts && mkdir /root/target-scripts
COPY *.sh /root/
COPY scripts/*.sh /root/scripts/
COPY target-scripts/*.sh /root/target-scripts/

RUN cd /root && ./prepare-pkgs.sh && dnf install -y git && dnf clean all
#RUN cd /root && ./install-docker.sh && dnf clean all
