FROM centos:7

RUN yum install -y sudo && yum clean all

RUN mkdir /root/scripts

COPY prepare-*.sh /root/
RUN cd /root && ./prepare-pkgs.sh && yum clean all

COPY install-*.sh /root/
RUN cd /root && ./install-docker.sh && yum clean all

#COPY requirements.txt /root/
#RUN cd /root && ./prepare-py.sh
