FROM ubuntu:20.04

RUN apt update \
    && apt install -y sudo tzdata \
    && apt clean all

RUN mkdir /root/scripts
COPY prepare-*.sh requirements.txt /root/
COPY scripts/* /root/scripts/

RUN cd /root && ./prepare-pkgs.sh
#RUN cd /root && ./prepare-py.sh
RUN cd /root && ./install-docker.sh || exit 0  # ignore error
