FROM ubuntu:22.04

RUN apt update \
    && apt upgrade -y \
    && apt install -y sudo tzdata \
    && apt clean all

#RUN mkdir /root/scripts && mkdir /root/target-scripts
#COPY *.sh /root/
#COPY scripts/*.sh /root/scripts/
#COPY target-scripts/*.sh /root/target-scripts/

#RUN cd /root && ./prepare-pkgs.sh && apt install -y git && apt clean all
#RUN cd /root && ./install-docker.sh && apt clean all
