FROM almalinux:9

RUN dnf install -y sudo dnf 'dnf-command(download)' && dnf clean all

RUN mkdir /root/scripts && mkdir /root/target-scripts
COPY target-scripts/config.sh /root/target-scripts/
COPY prepare-*.sh install-*.sh /root/

RUN cd /root && ./prepare-pkgs.sh && dnf install -y git && dnf clean all
RUN cd /root && ./install-docker.sh && dnf clean all

#COPY requirements.txt /root/
#RUN cd /root && ./prepare-py.sh
