FROM centos:7

RUN yum install -y sudo && yum clean all

COPY prepare-*.sh requirements.txt /root
RUN cd /root && ./prepare-pkgs.sh
RUN cd /root && ./prepare-py.sh
RUN cd /root && ./prepare-docker.sh
