#!/bin/bash
KUBESPRAY_VERSION=${KUBESPRAY_VERSION:-2.19.1}
#KUBESPRAY_VERSION=${KUBESPRAY_VERSION:-master}

REGISTRY_PORT=${REGISTRY_PORT:-35000}

# TODO: These version must be same as kubespray.
RUNC_VERSION=1.1.1
CONTAINERD_VERSION=1.6.4
NERDCTL_VERSION=0.19.0
CNI_VERSION=1.1.1
