# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder "../../../", "/home/vagrant/kubespray-offline", owner: "vagrant", group: "vagrant", type: "rsync"

  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provider :libvirt do |lv|
    lv.memory = 2048
    lv.cpus = 2
    lv.machine_virtual_size = 80
  end

  config.vm.define "ubuntu26" do |c|
    c.vm.hostname = "ubuntu26"
    c.vm.box = "cloud-image/ubuntu-26.04"
    #c.vm.box = "bento/ubuntu-26.04"
    c.vm.network "private_network", ip: "192.168.56.67"
  end

  config.vm.define "ubuntu24" do |c|
    c.vm.hostname = "ubuntu24"
    c.vm.box = "cloud-image/ubuntu-24.04"  # Can use machine_virtual_size
    #c.vm.box = "bento/ubuntu-24.04"
    c.vm.network "private_network", ip: "192.168.56.63"
  end

  config.vm.define "ubuntu22" do |c|
    c.vm.hostname = "ubuntu22"
    c.vm.box = "cloud-image/ubuntu-22.04"  # Can use machine_virtual_size
    #c.vm.box = "generic/ubuntu2204"
    c.vm.network "private_network", ip: "192.168.56.64"
  end

  config.vm.define "rocky9" do |c|
    c.vm.hostname = "rocky9"
    c.vm.box = "generic/rocky9"
    c.vm.network "private_network", ip: "192.168.56.65"
  end

  config.vm.define "alma8" do |c|
    c.vm.hostname = "alma8"
    #c.vm.box = "almalinux/8" # root fs is too small...
    c.vm.box = "bento/almalinux-8"
    c.vm.network "private_network", ip: "192.168.56.66"
  end
end
