# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  config.vm.define "ubuntu24" do |c|
    c.vm.hostname = "ubuntu24"
    c.vm.box = "bento/ubuntu-24.04"
    c.vm.network "private_network", ip: "192.168.56.63"
    c.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    c.vm.synced_folder "../../../", "/home/vagrant/kubespray-offline", owner: "vagrant", group: "vagrant"
  end

  config.vm.define "ubuntu22" do |c|
    c.vm.hostname = "ubuntu22"
    c.vm.box = "generic/ubuntu2204"
    c.vm.network "private_network", ip: "192.168.56.64"
    c.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    c.vm.synced_folder "../../../", "/home/vagrant/kubespray-offline", owner: "vagrant", group: "vagrant"
  end

  config.vm.define "alma8" do |c|
    c.vm.hostname = "alma8"
    #c.vm.box = "almalinux/8" # root fs is too small...
    c.vm.box = "bento/almalinux-8"
    c.vm.network "private_network", ip: "192.168.56.65"
    c.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    c.vm.synced_folder "../../../", "/home/vagrant/kubespray-offline", owner: "vagrant", group: "vagrant"
  end
end
